# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr2d = np.reshape(arr, (2, 5))
print(arr2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack((a, b))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.hstack((a, b))


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
my_another_array = np.array ([[0, 1, 3],[4, 5, 6],[7, 8, 9]]) 
my_another_array.flatten()

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
higher_dim = np.array ([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]) 
res = higher_dim.flatten()
res

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
array_one = np.array ([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]]) 
array_one.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr1 = np.random.random((5, 5))
arr2 = np.square(arr1)
arr2

array([[3.65789882e-01, 5.45991130e-02, 6.40028662e-01, 1.17996457e-04,
        1.43875448e-02],
       [4.56266035e-01, 6.98405183e-02, 4.82778684e-01, 2.49802722e-01,
        4.91579687e-01],
       [1.25850628e-01, 3.05768181e-02, 7.62683710e-02, 4.85360916e-01,
        4.00871354e-01],
       [1.11773797e-01, 9.21797951e-01, 1.99561026e-01, 4.74997693e-02,
        8.54974017e-01],
       [4.27074544e-01, 7.86418745e-01, 2.74379213e-01, 9.15218549e-01,
        9.84248940e-01]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
mean_array = np.random.random((5, 6)) 
actual_mean_array = np.mean(mean_array)
actual_mean_array

0.4953207953861253

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
std_array = np.random.random((5, 6)) 
actual_std_array = np.std(std_array)
actual_std_array

0.2833267767864054

## Question:10

### Find the median of the previous array in Q8?

In [10]:
med_array = np.random.random((5, 6)) 
actual_med_array = np.median(med_array)
actual_med_array

0.5065470187009209

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
tran_array = np.random.random((5, 6)) 
actual_tran_array = np.transpose(tran_array)
actual_tran_array

array([[0.96673222, 0.81235196, 0.19407539, 0.25553001, 0.36499032],
       [0.28589577, 0.90043689, 0.50136737, 0.13270537, 0.1089826 ],
       [0.73176744, 0.58561206, 0.03666269, 0.23957128, 0.02137156],
       [0.71318479, 0.38494562, 0.79745386, 0.18443761, 0.40010086],
       [0.10370058, 0.51578291, 0.15813529, 0.54232634, 0.13370317],
       [0.13472093, 0.23501253, 0.08406277, 0.18070447, 0.65591137]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [13]:
a = np.arange(1, 17).reshape(4,4)
sum_array = np.trace(a)
sum_array

34

## Question:13

### Find the determinant of the previous array in Q12?

In [14]:
a1_array = np.array([[ 1,  2,  3,  4],
                     [ 5,  6,  7,  8],
                     [ 9, 10, 11, 12],
                     [13, 14, 15, 16]])

deter_array = np.linalg.det(a1_array)
deter_array

4.7331654313261276e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [15]:
perc_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
perc_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
another_array = np.percentile(perc_array, 50)
another_array

4.5

In [17]:
another_array = np.percentile(perc_array, 95)
another_array

8.549999999999999

## Question:15

### How to find if a given array has any null values?

In [18]:
my_own_array = np.array([0, 1, 2, 3, 4, 5, 6])
array_has_nan = np.isnan(my_own_array)
array_has_nan

array([False, False, False, False, False, False, False])