# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
null_vector = np.zeros(10, dtype=int)
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [4]:
another_vector = np.arange(10, 49)
another_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [5]:
another_vector.shape

(39,)

5. Print the type of the previous array in question 3

In [6]:
another_vector.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [9]:
np.__version__, np.show_config()


blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/RIZWAN/anaconda3\\Library\\include']


('1.19.2', None)

7. Print the dimension of the array in question 3


In [10]:
another_vector.ndim

1

8. Create a boolean array with all the True values

In [12]:
boolean_array = np.array(range(10), dtype=bool)
boolean_array

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [16]:
two_dim_array = np.zeros((2, 2))
two_dim_array

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [17]:
three_dim_array = np.zeros((3, 3, 3))
three_dim_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [19]:
original_vector = np.array(range(1, 10))
print("original_vector is:", original_vector) 
reversed_vector = original_vector[::-1]
print("reversed_vector is", reversed_vector)


original_vector is: [1 2 3 4 5 6 7 8 9]
reversed_vector is [9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [27]:
nill_vector = np.zeros(10)
nill_vector[4] = 1
nill_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [28]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [31]:
arr = np.array([1,2,3,4,5], dtype=float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [32]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.multiply(arr1, arr2)


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [36]:
arr4 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr5 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(np.greater(arr4, arr5))


[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [38]:
arr[arr % 2 == 1]

array([1., 3., 5.])

18. Replace all odd numbers to -1 from previous array

In [40]:
arr[arr % 2 == 1] = [-1]
arr

array([-1.,  2., -1.,  4., -1.])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [43]:
arr = np.arange(10)
arr[arr >= 5] = [12]
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12, 12])

20. Create a 2d array with 1 on the border and 0 inside

In [48]:
two_D_array = np.ones((4, 4))
two_D_array[1:-1, 1:-1] = [0]
two_D_array

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [52]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1, 1] = 12
arr2d


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [53]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0, 0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [59]:
dim_2_array = np.arange(9).reshape(3, 3)
dim_2_array[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [61]:
dim_2_array = np.arange(9).reshape(3, 3)
dim_2_array[1][1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [63]:
dim_2_array = np.arange(9).reshape(3, 3)
dim_2_array[0:-1, 2]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [64]:
random_array = np.random.random((10, 10))
print("original_array:", random_array)
maxi_rand_array, mini_rand_array = random_array.max(), random_array.min()
print(maxi_rand_array,mini_rand_array)

original_array: [[0.08681454 0.79337521 0.61365915 0.24314563 0.93518587 0.13296217
  0.16743318 0.99839533 0.92035575 0.36295794]
 [0.25893166 0.45217158 0.21243741 0.00185551 0.67500464 0.95661941
  0.9616312  0.69948196 0.32678553 0.19765743]
 [0.76537785 0.74203055 0.18620074 0.89994382 0.7492221  0.79183118
  0.06285468 0.8331879  0.37756676 0.56283474]
 [0.02677636 0.19685361 0.35065653 0.39279168 0.45882508 0.9107212
  0.36301139 0.64861568 0.16488929 0.66420253]
 [0.0407687  0.27858283 0.25829784 0.78577242 0.10803849 0.00904736
  0.7098866  0.16261706 0.62047558 0.12171738]
 [0.56840731 0.34657095 0.00434859 0.01424323 0.1939326  0.1720639
  0.37714083 0.86933793 0.47281584 0.51861632]
 [0.48721885 0.5304859  0.67337265 0.11671467 0.19347482 0.44374625
  0.48960045 0.59779708 0.3462226  0.02465739]
 [0.78308807 0.0934098  0.41894993 0.5200313  0.98061332 0.96302373
  0.04036279 0.29327118 0.90736696 0.39679487]
 [0.66228449 0.27247337 0.95153982 0.34537844 0.62685594 0.4847006

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [65]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [72]:
import random
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where(name[data] != "Will"))


[1 5 3 2 1 4 4 6]
(array([0, 1, 2, 4, 7], dtype=int64),)


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [73]:
import random
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where((name[data] != "Joe") & (name[data] != "Will")))

[1 5 3 2]
(array([2], dtype=int64),)


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [76]:
D2_array = np.random.uniform(low=1.0, high=15.0,  size=(3, 3))
D2_array

array([[ 4.18101019,  2.72446573, 14.90717677],
       [ 4.12086888, 13.27478447, 10.05810457],
       [13.71661624,  1.42240379,  4.39118316]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [77]:
two_Dimen_array = np.random.uniform(low=1.0, high=16.0, size=((2, 2, 4)))
two_Dimen_array

array([[[10.5081444 ,  1.11310068,  9.63713296, 14.98301333],
        [ 9.23088939, 13.06020662, 12.99944896,  6.51280551]],

       [[12.02670733, 13.79477024, 10.37562231,  8.45422482],
        [ 7.73736203, 11.61662807, 13.79271242,  4.85250983]]])

33. Swap axes of the array you created in Question 32

In [78]:
np.swapaxes(two_Dimen_array, 0, 1)
two_Dimen_array

array([[[10.5081444 ,  1.11310068,  9.63713296, 14.98301333],
        [ 9.23088939, 13.06020662, 12.99944896,  6.51280551]],

       [[12.02670733, 13.79477024, 10.37562231,  8.45422482],
        [ 7.73736203, 11.61662807, 13.79271242,  4.85250983]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [86]:
my_array = np.arange(10, dtype=int)
np.sqrt(my_array)



array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [90]:
my_array = np.where(my_array >= 0.5, 0, my_array)
my_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [91]:
import numpy as geek
my_array1 = np.random.random(12)
my_array2 = np.random.random(12)
maximum_array = geek.maximum(my_array1, my_array2)
maximum_array

array([0.54417167, 0.9186203 , 0.8234865 , 0.37267669, 0.97306955,
       0.73532713, 0.3488453 , 0.89067384, 0.44356987, 0.52654985,
       0.74316951, 0.39156769])

36. 

---
Find the unique names and sort them out!


In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uni_array = np.unique(names)
uni_array

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [95]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
del_array = np.intersect1d(a, b)
a = filter(lambda x: x if x not in del_array else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [98]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray[:, 1] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [99]:
 x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
 y = np.array([[6., 23.], [-1, 7], [8, 9]])
 np.dot(x, y)
 

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [102]:
matrix_random = np.random.random(20)
Cumulative_sum = matrix_random.cumsum()
Cumulative_sum


array([ 0.5947321 ,  0.63546003,  0.98138496,  1.28459341,  2.04998552,
        2.79677862,  2.98181479,  3.34045594,  4.0052757 ,  4.62384202,
        5.31474505,  5.57728878,  6.55683806,  6.98090621,  7.04823981,
        7.86775612,  7.99538827,  8.56626153,  9.37916791, 10.01358335])